apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: arbetsprov-app
  labels:
    app: arbetsprov-app
spec:
  host: https://arbetsprov.testapp.se/
  port:
    targetPort: 8080 
  to:
    kind: Service
    name: arbetsprov-service